language: node_js
dist: xenial

node_js:
  - "10"

env:
  - CC=gcc-5 CXX=g++-5 VIPS_RPC_ADDRESS='http://user:pass@localhost:32916' SENDER_ADDRESS='vKbdhdXU8imLugnW3tpKTSovg4CCCUzMqM' WALLET_PASSPHRASE='pass'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

cache:
  directories:
    - "node_modules"

before_install:
  - wget https://github.com/y-chan/VIPSTARCOIN/releases/download/v1.0.2/VIPSTARCOIN-1.0.2-x86_64-linux-gnu.tar.gz

install:
  - tar -xvzf VIPSTARCOIN-1.0.2-x86_64-linux-gnu.tar.gz
  - npm install
  - mkdir test/data/.VIPSTARCOIN

script:
  - ./bin/VIPSTARCOINd -testnet -logevents -rpcuser=user -rpcpassword=pass -datadir=./test/data/.VIPSTARCOIN & 
  - sleep 10
  - npm run test:cleanenv

after_failure:
  - cat /home/travis/build/vipstar-dev/vweb3.js/test/data/.VIPSTARCOIN/testnet3/debug.log
